create_account:
    path: /create_account
    controller: App\Controller\CreateAccountController::index

create_account_server:
    path: /create_account_server
    controller: App\Controller\CreateAccountController::create

verify:
    path: /authentify
    controller: App\Controller\HomeController::authentify

admin:
    path: /admin
    controller: App\Controller\AdminController::createProduct

home:
    path: /
    controller: App\Controller\HomeController::index

controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation